name: Docker - Build and push latest

on:
  push:
    branches: [ '**' ]
    tags-ignore: [ 'release-*' ]
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  APP_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/app
  CONTENSIS_CLIENT_ID: aafd27eb-75b2-4b5b-8371-c5489082c710
  CONTENSIS_SHARED_SECRET: 9dc71260e4de430f956162a67345cc53-147c9d2fed75415788f9fdd321d255b1-2b734d1c6f3d471cb0d62157ac681f85

jobs:
  build-latest:
    name: Build Block
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Converys app image string case
        id: str
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.APP_IMAGE }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into the container registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image, tag and push to the registry
        id: build
        env:
          DOCKER_TAG: ${{ steps.str.outputs.lowercase }}:build-${{ github.run_number }}
        run: |
          echo "Building Docker Image"
          docker build -f Dockerfile . -t ${{ env.DOCKER_TAG }}
          echo "Built Successfully"
          echo "Pushing Docker Image"
          docker push ${{ env.DOCKER_TAG }}
          echo "Pushed Successfully"
        shell: bash
  deploy:
    name: Push block to Contensis
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs: build-latest
    steps:
      - name: Push block to Contensis
        id: push-block
        uses: contensis/block-push@v1
        with:
          block-id: wedding-website
          alias: blackpool
          project-id: lgWebsite
          client-id: ${{ env.CONTENSIS_CLIENT_ID }}
          shared-secret: ${{ env.CONTENSIS_SHARED_SECRET }}
          image-uri: ${{ env.APP_IMAGE }}:build-${{ github.run_number }}
